name: Rename and Move Files

on:
  push:

jobs:
  rename-and-move:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Check if commit message matches format
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        # 提取 commit message 中的字段
        if [[ "$COMMIT_MESSAGE" =~ ^([^,]+),([^,]+),([^,]+),([^,]+),([^,]+)$ ]]; then
          echo "TIME=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          echo "TITLE=${BASH_REMATCH[2]}" >> $GITHUB_ENV
          echo "CONF=${BASH_REMATCH[3]}" >> $GITHUB_ENV
          echo "YEAR=${BASH_REMATCH[4]}" >> $GITHUB_ENV
          echo "NAME=${BASH_REMATCH[5]}" >> $GITHUB_ENV
        else
          echo "Commit message does not match the format, exiting." && exit 0
        fi

    - name: Rename and move PDF and PPT/PPTX files
      run: |
        PDF_FILE=$(git diff --name-only --diff-filter=A HEAD^ HEAD | grep -i '.pdf') || true
        PPT_FILE=$(git diff --name-only --diff-filter=A HEAD^ HEAD | grep -i '.pptx\|.ppt') || true
    
        # 检查是否找到了文件
        if [ -z "$PDF_FILE" ] || [ -z "$PPT_FILE" ]; then
          echo "No PDF or PPT files found. Exiting."
          echo "SHOULD_CONTINUE=false" >> $GITHUB_ENV
          exit 0  # 直接退出
        fi
        echo "SHOULD_CONTINUE=true" >> $GITHUB_ENV
        if [ -n "$PDF_FILE" ]; then
          mv "$PDF_FILE" "PDF/${TIME}.pdf"
        fi
        if [ -n "$PPT_FILE" ]; then
          EXTENSION="${PPT_FILE##*.}"
          mv "$PPT_FILE" "PPT/${TIME}.${EXTENSION}"
        fi

    - name: Insert formatted comment into README.md
      if: env.SHOULD_CONTINUE == 'true'
      run: |     
        # 确认PPT文件的扩展名
        PPT_EXTENSION=$(ls PPT/${TIME}.pptx 2>/dev/null && echo "pptx" || echo "ppt")
        
        # 创建插入的格式
        FORMATTED_MESSAGE="| $TIME | $TITLE | $CONF | $YEAR | [PDF](./PDF/${TIME}.pdf)/[PPT](./PPT/${TIME}.${PPT_EXTENSION}) | $NAME |"
        
        # 插入到 README.md 的第 17 行
        sed -i "17i $FORMATTED_MESSAGE" README.md

    - name: Commit and push changes
      if: env.SHOULD_CONTINUE == 'true'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add PDF/${TIME}.pdf PPT/${TIME}.* README.md
        git commit -m "Renamed files and updated README with commit message: $COMMIT_MESSAGE"
        git push
